#!/usr/bin/env ruby

require 'date'
require_relative 'roam_date'

# {{query: {and: [[October 9th, 2020]] [[TODO]] [[Next Actions ✅]]}}}
def query_for_dates(dates)
  dates = dates.map {|date|
    "[[#{RoamDate.roam_date(date)}]]"
  }.join(" ")
  date_subquery = "{or: #{dates}}"
  "{{query: {and: #{date_subquery} [[TODO]] [[Next Actions ✅]] {not: {and: [[Query]]}}}}} #Query"
end

def roam_priority_query(date)
  # things due today (day 0)
  # things due tomorrow (day 1)
  # things due in days 2-6
  puts <<-QUERY
- Things due today
  - #{query_for_dates([Date.today])}
- Things due tomorrow
  - #{query_for_dates([Date.today+1])}
- Things due the rest of the week
  - #{query_for_dates((2..6).map {|i| Date.today + i})}
  QUERY
end

def date_from_args(args)
  if args.count == 0
    Date.today
  else
    Date.parse(args[0])
  end
end

if __FILE__ == $0
  roam_priority_query(date_from_args(ARGV))
end
