#!/usr/bin/env ruby

require 'set'
require 'date'
require_relative 'roam_month'


def to_markdown(node, depth=0)
  result = []
  result << "  "*depth + "- " + node["string"]
  node["children"].each do |child|
    result.push(*to_markdown(child, depth+1))
  end
  result
end

# TODO: proper args, allow specifying a range, month containing date, etc
def dates_from_args(args)
  if args.count == 0
    RoamCalendar.month_range_containing_date(Date.today)
  elsif args.count == 1
    RoamCalendar.month_range_containing_date(Date.parse(args[0]))
  else
    args.map {|arg| Date.parse(arg)}
  end
end

if __FILE__ == $0
  node = RoamCalendar.roam_calendar(dates_from_args(ARGV))
  puts to_markdown(node).join("\n")
end
